version: 2.1
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run: echo "Hello World!"
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Compile
          command: ./gradlew assembleDebug

  commit:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - run: echo "commit"

  acceptance:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - run: echo "acceptance"

  manual_test:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - run: echo "manual_test"

  release:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - run: echo "release"

workflows:
  version: 2.1
  deployment_pipeline:
    jobs:
      - commit
      - acceptance:
          requires:
            - commit
      - manual_test:
          requires:
            - acceptance
      - release:
          requires:
            - manual_test