version: 2.1
jobs:
  build:
    docker:
        - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "Hello World!"

  commit:
    working_derectory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - run: echo "commit"

  acceptance:
    working_derectory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - run: echo "acceptance"

  manual_test:
    working_derectory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - run: echo "manual_test"

  release:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - run: echo "release"

workflows:
  version: 2.1
  helloworld:
    jobs:
      - build